# Generated by Django 4.1.9 on 2023-06-26 21:07

from django.db import migrations
import my_awesome_project.fines.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="israeli_id",
            field=my_awesome_project.fines.models.CardIDField(blank=True, null=True, unique=True),
        ),
    ]
