# Generated by Django 4.1.9 on 2023-06-27 10:23

from django.db import migrations
import my_awesome_project.fines.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_israeli_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="israeli_id",
            field=my_awesome_project.fines.models.CardIDField(default=111111111, unique=True),
            preserve_default=False,
        ),
    ]
